/// Flutter icons EndocareIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EndocareIcons
///      fonts:
///       - asset: fonts/EndocareIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EndocareIcons {
  EndocareIcons._();

  static const _kFontFam = 'EndocareIcons';
  static const String? _kFontPkg = null;

  static const IconData icone_chavesenha = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icone_calendario = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icone_versenha = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icone_tabela = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icone_estatisticafinal = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icone_notificacao = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icone_glicose = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icone_cadeado = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icone_livro = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
